bsp: ccu-sunxi-rtc: add missing platform_device.h include
v7.1 header dependency graph no longer transitively pulls
<linux/platform_device.h> for this file, causing:
  error: invalid use of undefined type 'struct platform_device'
  error: implicit declaration of function 'platform_get_resource'
  error: implicit declaration of function 'platform_set_drvdata'
  error: implicit declaration of function 'platform_get_drvdata'
  error: 'struct platform_driver' has no member named 'probe'
  error: implicit declaration of function 'platform_driver_register'

Explicitly include the header.

Signed-off-by: Honsun Zhu <honsun@linux.com>