bsp: forward-declare round_rate before .determine_rate shim
Previous commit placed the shim wrapper at the top of each file
(after #includes) but the underlying round_rate function is defined
much later, so gcc barfs with:
  error: implicit declaration of function 'ccu_gate_round_rate';
    did you mean 'ccu_gate_round_rate_shim'?
  error: conflicting types for 'ccu_gate_round_rate'

Add a forward declaration of the round_rate function right before
the shim in each of the 8 affected files.

Signed-off-by: Honsun Zhu <honsun@linux.com>